name: Sync Org Repos
on:
  workflow_dispatch:  # 允许手动触发

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: "github/gitgordon85"
          dst: "gitee/gordon85"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "IPV6-IPTV"
          account_type: "user"  # 根据账号类型选择 org/user
          force_update: true
          debug: true
